server:
    port: 8081

spring:
    application:
        name: order-service

    datasource:
        url: jdbc:postgresql://localhost:5432/orders_db
        username: postgres
        password: postgres

    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: none
        show-sql: true
        properties:
            hibernate:
                jdbc:
                    time_zone: Asia/Kolkata

    jackson:
        time-zone: Asia/Kolkata

    kafka:
        bootstrap-servers: localhost:9092

        producer:
            acks: all
            retries: 3
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

logging:
    level:
        org:
            hibernate:
                SQL: DEBUG
            springframework:
                kafka: INFO